// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXJOLXZ-ci62cRfZ7N5JPeRT2t8Kf7ACA',
    appId: '1:1031094040861:web:a147e6fa1f8c4b606809f4',
    messagingSenderId: '1031094040861',
    projectId: 'money-tracker-app-89c86',
    authDomain: 'money-tracker-app-89c86.firebaseapp.com',
    storageBucket: 'money-tracker-app-89c86.firebasestorage.app',
    measurementId: 'G-WMJ3E0V4LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-0JzS8B8iJzyytMD8QxCxGkfvy6fA5w4',
    appId: '1:1031094040861:android:9669557184ae97a56809f4',
    messagingSenderId: '1031094040861',
    projectId: 'money-tracker-app-89c86',
    storageBucket: 'money-tracker-app-89c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNAGFmH87zCTwWAiwQ1mUxnIjN0GKyJQ',
    appId: '1:1031094040861:ios:019aadf7f0bfc6886809f4',
    messagingSenderId: '1031094040861',
    projectId: 'money-tracker-app-89c86',
    storageBucket: 'money-tracker-app-89c86.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNAGFmH87zCTwWAiwQ1mUxnIjN0GKyJQ',
    appId: '1:1031094040861:ios:019aadf7f0bfc6886809f4',
    messagingSenderId: '1031094040861',
    projectId: 'money-tracker-app-89c86',
    storageBucket: 'money-tracker-app-89c86.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXJOLXZ-ci62cRfZ7N5JPeRT2t8Kf7ACA',
    appId: '1:1031094040861:web:97ba99a30da84b136809f4',
    messagingSenderId: '1031094040861',
    projectId: 'money-tracker-app-89c86',
    authDomain: 'money-tracker-app-89c86.firebaseapp.com',
    storageBucket: 'money-tracker-app-89c86.firebasestorage.app',
    measurementId: 'G-N4J1PBTLWC',
  );
}
